language: r
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages

r_packages:
  - knitr

install: 
  # Needs to be done on bionic for now
  - sudo apt update -qq
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  - sudo apt-get install -qq libqt5svg5-dev
  # Qwt
  - sudo apt-get install -qq libqwt-qt5-dev
  # R packages
  - Rscript -e 'install.packages(c("dplyr", "knitr", "Rcpp", "testthat", "rmarkdown"))'
  # cppcheck
  #- sudo apt-get install -qq cppcheck
  # Codecov
  #- sudo pip install codecov
  # GSL
  #- my_github=${PWD##*/}  
  #- cd ..
  #- git clone https://github.com/Microsoft/GSL
  #- cd $my_github
  # OCLint
  #- ./install_oclint
  # GraphViz
  #- sudo apt-get install -qq graphviz

services:
 - xvfb

before_script:
  - ./scripts/download_other_githubs
  ###############################################
  # Go into the C++ folder
  ###############################################
  - cd cpp
  ###############################################
  # Build and run the tests for Damian and Dave
  ###############################################
  # elly_svg
  - qmake elly_svg.pro; make debug --silent; ./elly_svg
  ###############################################
  # Build and run the tests
  ###############################################
  # elly_test
  - qmake elly_test.pro; make debug --silent; ./elly_test
  ###############################################
  # Build and run (when possible) the command line applications
  ###############################################
  # daic
  #- qmake daic.pro; make debug --silent; ./daic
  # elly
  - qmake elly.pro
  - make debug --silent
  - ./elly
  - ./elly --create
  - cat parameters_1.txt
  - ./elly parameters_1.txt || true
  - cat parameters_2.txt
  - ./elly parameters_2.txt || true
  - cat parameters_3.txt
  - ./elly parameters_3.txt || true
  ###############################################
  # Build (not run) the GUIs
  ###############################################
  # elly
  #- qmake -qt=qt5 elly_gui.pro
  #- time make debug --silent
  #- (./elly_gui --run &) 
  ###############################################
  # Profiling, requires a rebuild in release mode
  ###############################################
  # elly
  #- qmake elly.pro
  #- make release --silent
  #- time ./elly --profile
  #- gprof elly > gprof.log
  #- head gprof.log
  ###############################################
  # Go out of the C++ folder
  ###############################################
  - cd ..
  ###############################################
  # cppcheck
  ###############################################
  # cppcheck
  #- cppcheck --quiet --error-exitcode=1 . 
  ###############################################
  # Code coverage
  ###############################################
  #- ./get_code_cov >/dev/null
  #- codecov >/dev/null
  ###############################################
  # OCLint
  ###############################################
  #- ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Download thesis
  - Rscript -e 'download.file("https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf", tempfile())'


