language: R
dist: bionic
cache: packages

r_packages:
  - devtools
  - DDD
  - DAISIE

before_install:
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev

after_install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  - sudo apt-get install -qq libqt5svg5-dev
  # Qwt
  - sudo apt-get install -qq libqwt-qt5-dev
  # gcov
  #- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  # cppcheck
  #- sudo apt-get install -qq cppcheck
  # Codecov
  #- sudo pip install codecov
  # GSL
  #- my_github=${PWD##*/}  
  #- cd ..
  #- git clone https://github.com/Microsoft/GSL
  #- cd $my_github
  # OCLint
  #- ./install_oclint
  # GraphViz
  #- sudo apt-get install -qq graphviz

services:
 - xvfb

before_script:
  - ./scripts/download_other_githubs
  ###############################################
  # Go into the C++ folder
  ###############################################
  - cd cpp
  ###############################################
  # Build and run the tests
  ###############################################
  # elly_test
  - qmake elly_test.pro; make debug --silent; ./elly_test
  ###############################################
  # Build and run (when possible) the command line applications
  ###############################################
  # daic
  #- qmake daic.pro; make debug --silent; ./daic
  # elly
  - qmake elly.pro
  - make debug --silent
  - ./elly
  - ./elly --create
  - cat parameters_1.txt
  - ./elly parameters_1.txt || true
  - cat parameters_2.txt
  - ./elly parameters_2.txt || true
  - cat parameters_3.txt
  - ./elly parameters_3.txt || true
  ###############################################
  # Build (not run) the GUIs
  ###############################################
  # elly
  #- qmake -qt=qt5 elly_gui.pro
  #- time make debug --silent
  #- (./elly_gui --run &) 
  ###############################################
  # Profiling, requires a rebuild in release mode
  ###############################################
  # elly
  #- qmake elly.pro
  #- make release --silent
  #- time ./elly --profile
  #- gprof elly > gprof.log
  #- head gprof.log
  ###############################################
  # Go out of the C++ folder
  ###############################################
  - cd ..
  ###############################################
  # cppcheck
  ###############################################
  # cppcheck
  #- cppcheck --quiet --error-exitcode=1 . 
  ###############################################
  # Code coverage
  ###############################################
  #- ./get_code_cov >/dev/null
  #- codecov >/dev/null
  ###############################################
  # OCLint
  ###############################################
  #- ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)

